sudo: required
env:
  global:
    - secure: ghh9HZ8BsJRu3dnQI1VuroSb4S2EtMrXdbfKT2spDavJAiTQnyP7fPYtmSASjFLI+RnNKA3SLueWCIL7VPcFbNol8gZrpp13kTBss8+5he1gupON3kCeLFmS36+QfOvWjoc/hd8kMUi3/6ciKMTq1cgBdrkdkscxPdzqO6h8XV7uTr03uNYzgo1R5P/c$
    - DOCKER_IMAGE=imduffy15/docker-gcloud
    - DOCKER_TAG=0.0.3
services:
  - docker
script:
  - docker build --build-arg VCS_REF=`git rev-parse --short HEAD` --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` -t $DOCKER_IMAGE:$DOCKER_TAG .
  - docker tag $DOCKER_IMAGE:$DOCKER_TAG $DOCKER_IMAGE:latest
after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push $DOCKER_IMAGE:$DOCKER_TAG
  - docker push $DOCKER_IMAGE:latest
